name: CI 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql
          coverage: pcov
          tools: composer

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create external Docker network
        run: |
          docker network inspect study-on_default || docker network create study-on_default

      - name: Setup environment and install dependencies
        run: |
          echo "DATABASE_URL=pgsql://postgres:admin@postgres:5432/study_on" > .env.local
          composer install

      - name: Build and start containers
        run: |
          mkdir -p ~/.yarn
          docker-compose build
          docker-compose up -d
          docker-compose exec -T php bash -c 'until pg_isready -h postgres -p 5432; do sleep 2; done;'

      - name: Install frontend dependencies
        run: |
          docker-compose run --rm -u root node yarn install
          docker-compose run --rm -u root node yarn encore dev

      - name: Initialize test environment
        run: |
          echo "DATABASE_URL=pgsql://postgres:admin@postgres:5432/study_on_test" > .env.test.local
          docker-compose exec -T php bin/console doctrine:database:drop --force --env=test || true
          docker-compose exec -T php bin/console doctrine:database:create --env=test
          docker-compose exec -T php bin/console doctrine:migrations:migrate -n --env=test
          docker-compose exec -T php bin/console doctrine:fixtures:load -n --env=test

      - name: Run tests
        run: docker-compose exec -T php bin/phpunit
